version: "3.9"
services:
  nginx:
    image: acrweba.azurecr.io/weba-nginx:1.6
    ports:
      - "80:80"
    depends_on:
      - middleware1
      - middleware2

  middleware1:
    image: acrweba.azurecr.io/weba-middleware:1.0
    expose:
      - "8080"
    environment:
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=8081

  middleware2:
    image: acrweba.azurecr.io/weba-middleware:1.0
    expose:
      - "8080"
    environment:
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=8081
