services:
  nginx:
    image: nginx:alpine
    ports: ["8088:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-algo/index.html:/usr/share/nginx/html/index.html:ro
      - ./web-algo/login.html:/usr/share/nginx/html/login.html:ro
      - ./web-algo/includes:/usr/share/nginx/html/includes:ro
    depends_on: [middleware1, middleware2]

  middleware1:
    build: ./middleware
    expose: ["8080"]

  middleware2:
    build: ./middleware
    expose: ["8080"]
