FROM nginx:alpine
COPY index.html /usr/share/nginx/html/
COPY login.html /usr/share/nginx/html/
COPY cadastro.html /usr/share/nginx/html/
COPY recuperar-senha.html /usr/share/nginx/html/
COPY includes /usr/share/nginx/html/includes/
