server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /home/logs/.positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_access
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          __path__: /home/logs/nginx/*.log

  - job_name: app_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: middleware
          __path__: /home/logs/app/*.log
