server:
  http_listen_port: 9080
  grpc_listen_port: 0
clients:
  - url: http://loki:3100/loki/api/v1/push
positions:
  filename: /tmp/positions.yaml
scrape_configs:
  - job_name: containers
    static_configs:
      - targets: []
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
          container: $CONTAINER_NAME
