apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  namespace: webalgo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: webalgoacr.azurecr.io/middleware:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: app
        - containerPort: 8081
          name: metrics
        env:
        - name: WEB_ALGO_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: WEB_ALGO_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: middleware
  namespace: webalgo
spec:
  selector:
    app: middleware
  ports:
  - name: app
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 8081
    targetPort: 8081
  type: ClusterIP